text-code:
  max-outputs: -1

text:
  data-column: 1
  max-outputs: -1 
  outputs-per-rule: -1
  preserve-text: false
  active-rules: [
    "americanize_britishize_english",
    "contraction_expansions",
    "discourse_marker_substitution",
    "insert_abbreviation",
    "number_to_word",
    "correct_common_misspellings",
    "replace_abbreviation_and_acronyms",
    "synonym_substitution" 
  ]

code:
  data-column: 1
  max-outputs: -1
  outputs-per-rule: 100
  preserve-closest-block: false
  active-rules: [
    "add_assignment_to_equal_assignment",
    "boolean_exchange",
    "conditional_exp_to_single_if",
    "if_dividing",
    "infix_expression_dividing",
    "log_statement",
    "loop_exchange",
    "loop_if_continue_to_else",
    "permute_statement",
    "pp_to_add_assignment",
    "prepostfix_expression_dividing",
    "reorder_condition",
    "reverse_if_else",
    "single_if_to_conditional_exp",
    "statements_order_rearrangement",
    "switch_string_equal",
    "switch_to_if",
    "try_catch",
    "unused_statement",
    "var_declaration_dividing",
    "var_declaration_merging",
    "variable_renaming"
  ]